### ISSUE TITLE
Other: Advanced API work - implement image storage with required data

### ISSUE THREAD

**Issue by steveshumaker** [avcopan/painless-panes#38]
Going to start with S3 buckets as the method of storage. Will work on this after linking up the window saga

**Comment by steveshumaker** [comment]
Need to remember to specify AWS env variables. Probably best to create an IAM user for the team

**Comment by avcopan** [comment]
@steveshumaker regarding the env variables, you could update the INSTRUCTIONS.md file to pass along that info.

**Comment by avcopan** [comment]
Obviously the actual values will need to be shared privately, though.

**Comment by steveshumaker** [comment]
Yup, agreed. I'm close on this - the hangup right now is react-webcam provides a base64 encoded image. We can store these in AWS, but retrieving them is sort of a pain. When I get back from work/tonight I'm going to look into converting that base64 to a Blob and storing that, then we can access the picture directly by accessing the object in S3 rather than having to create an `img` tag with the src=base64 encoding of the picture.

In order to implement this in the most optimal way (so far), I've added a submit button to the webcam page. The button adds a window then updates the current window ID via the store. The saga that adds the window then dispatches the POST to the S3 bucket, uploading the (soon to be) file.

**Comment by avcopan** [comment]
> In order to implement this in the most optimal way (so far), I've added a submit button to the webcam page. The button adds a window then updates the current window ID via the store. The saga that adds the window then dispatches the POST to the S3 bucket, uploading the (soon to be) file.

One note about the logic here. The submit button should "not" be adding a new window. An initial window has already been created when we create the project. It should just be putting through a PUT request to update the current window with the new information (in this case the picture). New windows should only be added when the user clicks "Add a New Window" after the current window is *done*.

**Comment by steveshumaker** [comment]
>  An initial window has already been created when we create the project. It should just be putting through a PUT request to update the current window with the new information (in this case the picture). New windows should only be added when the user clicks "Add a New Window" after the current window is _done_.

Do we have this built it? I'm at work so looking through GH isn't super helpful, but if I remember correctly we don't have that implemented. I also don't see a window being created in the `addUser query` or the `addProject query`. Can we discuss this tonight? I don't know if we _need_ the current window ID before we take a picture (as long as that's the first picture-related action). That way, windows will only be added with POSTs and updated with PUTs, rather than one added with a PUT and additional windows added with POSTs. I think it also might be helpful to take some time tonight and walk through the app's interactions and document specifically when things should be created versus when they should be updated - I'm sure we probably talked about this, I'm just not remembering and couldn't find it in Slack.

**Comment by avcopan** [comment]
Shoot -- I had implemented this, but it looks like my changes got wiped out in that messed-up PR. It's an easy fix, though.

From my perspective, the advantages of separating the window-creation POST request from the form-entry PUT requests are:

1. It makes the edit functionality automatic. We just take them back to the page and set `currentWindowId` to the window they want to edit, and everything else will work as expected.
2. That, in turn, makes a lot of other things much more intuitive from a user perspective. If, for any reason, their connection gets interrupted, or they take a lunch break, or they refresh, or they simply decide they didn't like the picture they just submitted, this implementation has the intuitive result of allowing them to pick up where they left off and continue editing the same window. The other implementation, triggering a POST request, forces them to create a new window when they don't want to (and don't expect to, because they haven't clicked the "Add a New Window Button!).
3. Since the other pieces of information (height, width, and frame type) have to be PUT requests anyway, this also just keeps things more consistent. Every part of the form behaves the same way, triggering a PUT request on the current window.

My initial thinking was to do what you're saying, but I realized that this ends up being very counterintuitive when I noticed what was happening with the zip code entry form. Every time I clicked "Next" on that page, I was creating a whole new project and orphaning the project that I had started with.

**Comment by avcopan** [comment]
@steveshumaker see PR #54 that I just requested your review on. We can discuss it tonight, but I wanted to have it ready to go, since this is how things were currently set up to work.

**Comment by steveshumaker** [comment]
What you dropped above makes sense to me! I just reviewed/merged, so I'll pull that into my fork tonight then update my implementation. Should be a quick modification of a couple lines in my stuff - thank you!

Side note - do we know if anything else got lost in that PR, off the top of your head? Maybe if/when we walk thru flow of the app by API call we can verify that we either have all routes either a. implemented, and/or b. documented.

**Comment by avcopan** [comment]
Sounds good! This is the only feature I was working on in that PR, so hopefully this is it. If anything else got lost, it would have been bug fixes on someone else's code (for example the getListOfWindows query).
